package com.curso.lenguasdeseñas.dominio.model.model.escuelamodel

import com.curso.lenguasdeseas.R

sealed class EscuelaInfo (val img: Int, val img1: Int, val name: Int, val descr: Int){
    data object Escuela : EscuelaInfo  (R.drawable.len_4, R.drawable.len_4, R.string.escuela, R.string.escul)
    data object Educacion : EscuelaInfo(R.drawable.len_4, R.drawable.len_4, R.string.educacion, R.string.educac)
    data object Jardindeinfantes : EscuelaInfo(R.drawable.len_4, R.drawable.len_4, R.string.jardinf, R.string.jain)
    data object Escuelaprimaria : EscuelaInfo (R.drawable.len_4, R.drawable.len_4, R.string.escuepri, R.string.espri)
    data object Secundaria: EscuelaInfo(R.drawable.len_4, R.drawable.len_4, R.string.secundaria, R.string.secund)
    data object Terviaria : EscuelaInfo(R.drawable.len_4, R.drawable.len_4, R.string.terciaria, R.string.tercia)
    data object Instituto : EscuelaInfo(R.drawable.len_4, R.drawable.len_4, R.string.instituto, R.string.instit)
    data object Privado : EscuelaInfo  (R.drawable.len_4, R.drawable.len_4, R.string.privado, R.string.privad)
    data object Publico : EscuelaInfo  (R.drawable.len_4, R.drawable.len_4, R.string.publico, R.string.publi)
    data object Curso : EscuelaInfo    (R.drawable.len_4, R.drawable.len_4, R.string.curso, R.string.curs)
    data object Universidad:EscuelaInfo(R.drawable.len_4, R.drawable.len_4, R.string.universidad, R.string.univerdid)
    data object Facultad : EscuelaInfo (R.drawable.len_4, R.drawable.len_4, R.string.dfacultad, R.string.facu)
    data object DirectorA: EscuelaInfo (R.drawable.len_4, R.drawable.len_4, R.string.director, R.string.direct)
    data object VicedirectorA : EscuelaInfo(R.drawable.len_4, R.drawable.len_4, R.string.vicedirect, R.string.vicedirect)
    data object Acto : EscuelaInfo     (R.drawable.len_4, R.drawable.len_4, R.string.acto, R.string.ac)
    data object ProfesorA : EscuelaInfo(R.drawable.len_4, R.drawable.len_4, R.string.profesor, R.string.profe)
    data object MaestroA : EscuelaInfo (R.drawable.len_4, R.drawable.len_4, R.string.maestro, R.string.maest)
    data object EstudianteAlumnoA : EscuelaInfo(R.drawable.len_4, R.drawable.len_4, R.string.estudiante, R.string.estudi)
    data object Comenzar : EscuelaInfo(R.drawable.len_4, R.drawable.len_4, R.string.comenzar, R.string.comenza)
    data object Informar : EscuelaInfo(R.drawable.len_4, R.drawable.len_4, R.string.informar, R.string.info)
    data object Aprender : EscuelaInfo(R.drawable.len_4, R.drawable.len_4, R.string.aprender, R.string.apren)
    data object Estudiar : EscuelaInfo(R.drawable.len_4, R.drawable.len_4, R.string.estudiar, R.string.estud)
    data object Recortar : EscuelaInfo(R.drawable.len_4, R.drawable.len_4, R.string.recortar, R.string.recort)
    data object Memorizar :EscuelaInfo(R.drawable.len_4, R.drawable.len_4, R.string.memeorizar, R.string.memo)
    data object Leer : EscuelaInfo    (R.drawable.len_4, R.drawable.len_4, R.string.leer, R.string.lee)
    data object Olvidar : EscuelaInfo (R.drawable.len_4, R.drawable.len_4, R.string.olvidar, R.string.olvid)
    data object Norecortar : EscuelaInfo(R.drawable.len_4, R.drawable.len_4, R.string.norecordar, R.string.norecord)
    data object Saber : EscuelaInfo  (R.drawable.len_4, R.drawable.len_4, R.string.saber, R.string.sab)
    data object Nosaber : EscuelaInfo(R.drawable.len_4, R.drawable.len_4, R.string.nosaber, R.string.nosab)
    data object Aprobar : EscuelaInfo(R.drawable.len_4, R.drawable.len_4, R.string.aprobado, R.string.aprob)
    data object Desprobar : EscuelaInfo   (R.drawable.len_4, R.drawable.len_4, R.string.desaaprobado, R.string.desaprob)
    data object ExamenRendir : EscuelaInfo(R.drawable.len_4, R.drawable.len_4, R.string.examen, R.string.exa)
    data object Practicar : EscuelaInfo   (R.drawable.len_4, R.drawable.len_4, R.string.practicar, R.string.practic)
    data object Completo : EscuelaInfo    (R.drawable.len_4, R.drawable.len_4, R.string.completo, R.string.complet)
    data object Fallar : EscuelaInfo      (R.drawable.len_4, R.drawable.len_4, R.string.fallar, R.string.fall)
    data object Corregir : EscuelaInfo    (R.drawable.len_4, R.drawable.len_4, R.string.corregir, R.string.correg)
    data object Enseñar : EscuelaInfo     (R.drawable.len_4, R.drawable.len_4, R.string.enseñar, R.string.enseñ)
    data object Pensar : EscuelaInfo(R.drawable.detail_mujer, R.drawable.detail_mujer, R.string.pensar, R.string.pens)
    data object Jugar : EscuelaInfo(R.drawable.detail_mujer, R.drawable.detail_mujer, R.string.jugar, R.string.jug)
    data object Escribir : EscuelaInfo(R.drawable.detail_mujer, R.drawable.detail_mujer, R.string.escribir, R.string.escrib)
    data object Responder : EscuelaInfo(R.drawable.detail_mujer, R.drawable.detail_mujer, R.string.responder, R.string.respon)
    data object Signar : EscuelaInfo(R.drawable.detail_mujer, R.drawable.detail_mujer, R.string.signar, R.string.sign)
    data object Contar : EscuelaInfo(R.drawable.detail_mujer, R.drawable.detail_mujer, R.string.contar, R.string.cont)
    data object Explicar : EscuelaInfo(R.drawable.detail_mujer, R.drawable.detail_mujer, R.string.explicar, R.string.explic)
    data object Terminar : EscuelaInfo(R.drawable.detail_mujer, R.drawable.detail_mujer, R.string.terminar, R.string.termin)
    data object Libro : EscuelaInfo(R.drawable.detail_mujer, R.drawable.detail_mujer, R.string.libro, R.string.libr)
    data object Carpeta : EscuelaInfo(R.drawable.detail_mujer, R.drawable.detail_mujer, R.string.carpeta, R.string.carpe)
    data object Fotocopia : EscuelaInfo(R.drawable.detail_mujer, R.drawable.detail_mujer, R.string.fotocopia, R.string.fotoc)
    data object Papelhoja : EscuelaInfo(R.drawable.detail_mujer, R.drawable.detail_mujer, R.string.papel, R.string.pape)
    data object Diplomadoa : EscuelaInfo(R.drawable.detail_mujer, R.drawable.detail_mujer, R.string.diplomado, R.string.dipplomad)
    data object Diccionario : EscuelaInfo(R.drawable.detail_mujer, R.drawable.detail_mujer, R.string.diccion, R.string.dicci)
    data object Lapicera : EscuelaInfo(R.drawable.detail_mujer, R.drawable.detail_mujer, R.string.lapicera, R.string.lapicer)
    data object Lapiz : EscuelaInfo(R.drawable.detail_mujer, R.drawable.detail_mujer, R.string.lapiz, R.string.lapi)
    data object Goma : EscuelaInfo(R.drawable.detail_mujer, R.drawable.detail_mujer, R.string.goma, R.string.gom)
    data object Pizarron : EscuelaInfo(R.drawable.detail_mujer, R.drawable.detail_mujer, R.string.pizarron, R.string.pazarr)
    data object Tema : EscuelaInfo(R.drawable.detail_mujer, R.drawable.detail_mujer, R.string.tema, R.string.tem)
    data object Ausente : EscuelaInfo(R.drawable.detail_mujer, R.drawable.detail_mujer, R.string.ausente, R.string.aus)
    data object Presente : EscuelaInfo(R.drawable.detail_mujer, R.drawable.detail_mujer, R.string.presente, R.string.presen)
    data object Vagoa : EscuelaInfo(R.drawable.detail_mujer, R.drawable.detail_mujer, R.string.vago, R.string.vag)
    data object Recreo : EscuelaInfo(R.drawable.detail_mujer, R.drawable.detail_mujer, R.string.recreo, R.string.recre)
    data object Atento : EscuelaInfo(R.drawable.detail_mujer, R.drawable.detail_mujer, R.string.atento, R.string.att)
    data object Desatento : EscuelaInfo(R.drawable.detail_mujer, R.drawable.detail_mujer, R.string.desatento, R.string.desatt)
    data object Distraido : EscuelaInfo(R.drawable.detail_mujer, R.drawable.detail_mujer, R.string.distraido, R.string.distrai)
    data object Interesadoa : EscuelaInfo(R.drawable.detail_mujer, R.drawable.detail_mujer, R.string.interesado, R.string.inter)
    data object Puntual : EscuelaInfo(R.drawable.detail_mujer, R.drawable.detail_mujer, R.string.puntual, R.string.punt)
    data object Nerviosoa : EscuelaInfo(R.drawable.detail_mujer, R.drawable.detail_mujer, R.string.nerviosoa, R.string.nervios)
    data object Responsable : EscuelaInfo(R.drawable.detail_mujer, R.drawable.detail_mujer, R.string.responsable, R.string.respons)

}